# Generated by Django 4.2.7 on 2023-11-22 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChampFormulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('type_de_champ', models.CharField(max_length=50)),
                ('obligatoire', models.BooleanField(default=True)),
                ('formulaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champs', to='app_blog.formulaire')),
            ],
        ),
    ]
