# Generated by Django 4.2.7 on 2023-11-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_formulaire_champformulaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='champformulaire',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
