# Generated by Django 4.2.7 on 2023-11-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_champformulaire_fichier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champformulaire',
            name='fichier',
        ),
        migrations.AlterField(
            model_name='champformulaire',
            name='type_de_champ',
            field=models.CharField(choices=[('texte', 'Texte'), ('fichier', 'Fichier')], max_length=50),
        ),
    ]
