# Generated by Django 4.2.7 on 2023-11-22 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_blog', '0004_remove_champformulaire_fichier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReponseFormulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='reponses/')),
                ('formulaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='app_blog.formulaire')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
