# Generated by Django 4.2.7 on 2023-11-22 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0005_reponseformulaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReponseChamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.TextField()),
                ('champ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='app_blog.champformulaire')),
                ('reponse_formulaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='app_blog.reponseformulaire')),
            ],
        ),
    ]
