# Generated by Django 4.2.7 on 2023-11-23 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_blog', '0008_reponseformulaire_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponseformulaire',
            name='utilisateur',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
