# Generated by Django 4.2.7 on 2023-12-04 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app_blog', '0009_alter_reponseformulaire_utilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaireGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.formulaire')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
    ]
