# Generated by Django 4.2.7 on 2023-12-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app_blog', '0010_formulairegroupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaire',
            name='groupes',
            field=models.ManyToManyField(related_name='formulaires', through='app_blog.FormulaireGroupe', to='auth.group'),
        ),
        migrations.AlterUniqueTogether(
            name='formulairegroupe',
            unique_together={('formulaire', 'groupe')},
        ),
    ]
